### ISSUE TITLE
Intermittent "Script error for: domReady"

### ISSUE THREAD

**Issue by nikolas** [requirejs/domReady#13]
In Firefox 37.0.1 and Chromium 41.0.2272.76, I get this error when loading my require.js app with domReady during the page load:
```
Error: Script error for: domReady
http://requirejs.org/docs/errors.html#scripterror
```

Then, when I refresh, the error doesn't occur again.

Many users on my site are getting this error, logged with a ravenjs/sentry setup.

**Comment by jrburke** [comment]
If you have a test case that can be tried, that would be helpful. If you have something on the page that triggers a reload or page navigation while the page is still loading, then I can see this error happening as the browser shuts down the current connections it has for the current page to switch to loading the new page.

**Comment by nikolas** [comment]
There's nothing triggering a reload, it's a pretty standard page. This is occurring in this Django app here: https://github.com/ccnmtl/dmt

I'm working on setting up automated testing for requirejs so it will be easier to come up with a test case.

**Comment by nikolas** [comment]
Maybe this issue is caused by a stray `$(document).ready` call I forgot to convert to requirejs `domReady`: https://github.com/ccnmtl/dmt/blob/master/media/js/src/main.js#L121

I'll convert it and update this.

**Comment by nikolas** [comment]
This issue was actually something I was doing wrong. It occurred on many users' browsers using a modified version of domReady that was waiting for `readyState === 'interactive'` (see #12). I reverted to the current, standard version of domReady and I'm no longer seeing these errors.
