### ISSUE TITLE
Installable via NPM?

### ISSUE THREAD

**Issue by dicksont** [requirejs/domReady#15]
NPM reports another package under the 'domready' handle. Is this one installable via NPM?

**Comment by jrburke** [comment]
With npm 2.12, this seems to work, since it knows how to install things from github:

    npm install requirejs/domReady

**Comment by dicksont** [comment]
OK, you just blew my mind there. I didn't know that install with github handle was possible with NPM. 
This method seems to work with 2.8.3 also, but not on another machine that I have with 2.13.3. I then upgraded to 3.3.6, but still no luck. Just wondering if this feature haven't been removed and if it is my setup that is messed up.

**Comment by jrburke** [comment]
Looking at https://docs.npmjs.com/cli/install which might be for 3.0, but this feature has been there for a while, it might help to add "github:" to the front, "github:requirejs/domReady". If that does not work, maybe it is an issue with mixed case in the domReady name? Trying requirejs/text might help determine if that is the issue.

**Comment by dicksont** [comment]
OK, thanks. Prepending the protocol worked. Now I am wondering how I can communicate this dependency in package.json. You have ideas?

**Comment by jrburke** [comment]
I would try `npm install --save ...` to see what it writes in the package.json

**Comment by dicksont** [comment]
That is pretty genius. But disappointingly nothing shows in package.json.

**Comment by jrburke** [comment]
This seems to work in npm 2.14. Specifying a version number as illustrated in that link to the install doc does not work, maybe that is a 3.0 thing. But this seems to work:

```
  "dependencies": {
    "domReady": "github:requirejs/domReady"
  }
```

**Comment by dicksont** [comment]
Oh, that works! 🎉💥🎊
