### ISSUE TITLE
New /updated tag so the bower.json file works

### ISSUE THREAD

**Issue by far-blue** [requirejs/domReady#16]
While a bower.json file was added as pull request #14 the 2.0.1 tag is still marking a previous commit so when bower pulls tag 2.0.1 the bower.json file is missing. Can you please either update the tag or tag with 2.0.2 or something so this is fixed?

**Comment by jrburke** [comment]
I updated the 2.0.1 and latest tags to point to the latest code, since the domReady.js has not changed between the origin placement of the tags and now.
