### ISSUE TITLE
Issue with yarn

### ISSUE THREAD

**Issue by marcoscaceres** [requirejs/domReady#20]
Not sure if this is directly related to domReady... but, given a package.json configuration:

```JSON 
{
  "devDependencies": {
    "domReady": "github:requirejs/domReady"
  }
}
```

Yarn install fails, because (I'm guessing here) it can't find the right package on NPM:

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/username/Library/Caches/Yarn/npm-domReady-2.0.1-3ab6964ba262be995e56452d91b6342f025d30ef'".
```

I'm wondering, could this library be published properly to NPM? I know npm and yarn can resolve github URLs, but it's nicer having things in NPM when looking things up.

**Comment by marcoscaceres** [comment]
(I raise this as it's causing our CI to fail: https://travis-ci.org/w3c/respec)

**Comment by jrburke** [comment]
This seems to be a growing pain with yarn. There are a few issues filed with yarn around fetching dependencies in git repos, [this one](https://github.com/yarnpkg/yarn/issues/513) seems to indicate that this form of the dependency name should work, and should also work with npm:

```
"domReady": "git+ssh://git@github.com/requirejs/domReady.git"
```

No plans to publish to npm for this repo.

**Comment by marcoscaceres** [comment]
> No plans to publish to npm for this repo.

I totally respect that, but just wondering what your rationale is for not publishing to npm?

**Comment by jrburke** [comment]
It is an extra step beyond what I need to normally here, which is just tag the release. I do not expect a high amount of change for this repo, and I think its technology is falling out of favor. 

The installed name will not end up as just "domReady", as it needs to be namespaced in some way to fit into npm's global namespace. The github URL allows the "global namespace" to be unique, but to just use "domReady" as the local module ID dependency.

So, mostly just feels like more of a hassle for the expected payoff for this repo, and some lingering annoyance at npm's global namespace affecting the local dependency name. I do appreciate that most other folks would not see these as big enough concerns to prevent npm publishing.

**Comment by marcoscaceres** [comment]
@jrburke, really appreciate you taking the time to write up the justification. Makes sense!
